version: '3.6'
services:
  mongo:
    image: mongo
    ports: 
    - 27017:27017
    volumes: 
    - ${PWD}/db:/data/db
  
  react: 
    image: node
    ports:
    - 3000:3000
    volumes:
    - ${PWD}/frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
  
  api:
    image: robbof/goapi:v0.1
    ports: 
    - 8080:8080

  
